import type { Project, Experience, Education, SkillCategory, Stat } from "@/types";

export const projects: Project[] = [
  {
    id: "ai-dashboard",
    title: "AI Business Analytics Dashboard",
    description: "Multi-tenant business intelligence platform with AI-generated insights",
    longDescription:
      "A multi-tenant BI platform where businesses upload CSV/XLSX sales, expense, inventory, and customer data to get real-time KPIs, revenue charts, and profit forecasts. Integrated with the Gemini API to generate natural-language summaries explaining key patterns and actionable business insights.",
    tech: ["Next.js", "TypeScript", "Supabase", "Gemini API"],
    features: [
      "CSV/XLSX data processing",
      "AI-generated business insights",
      "Revenue & profit dashboards",
      "KPI tracking across tenants",
      "Multi-tenant architecture",
      "Secure authentication",
    ],
    category: "Full Stack",
    gradient: "from-purple-600 to-pink-600",
    year: "2025",
    featured: true,
    tags: ["SaaS", "analytics", "gemini"],
    github: "https://github.com/jeet310704/ai-business-dashboard",
  },
  {
    id: "muscle-metrics",
    title: "MuscleMetrics",
    description: "Full-stack social fitness platform with real-time features",
    longDescription:
      "A full-stack MERN social fitness app for logging workouts, tracking streaks, and recording personal bests. Features real-time messaging, a live activity feed, and weekly/all-time leaderboards via Socket.IO and JWT auth. Includes an AI coach for personalized workout recommendations and progress charts.",
    tech: ["React", "Node.js", "Express", "MongoDB", "Socket.IO"],
    features: [
      "Workout logging & streak tracking",
      "Real-time leaderboards",
      "Peer messaging via Socket.IO",
      "Live activity feed",
      "AI workout recommendations",
      "JWT authentication",
    ],
    category: "Full Stack",
    gradient: "from-violet-600 to-indigo-600",
    year: "2024",
    featured: true,
    tags: ["social", "fitness", "real-time"],
    github: "https://github.com/jeet310704/musclemetrics",
  },
  {
    id: "hr-management",
    title: "HR Management System",
    description: "Full-stack HR platform with employee management and payroll",
    longDescription:
      "A comprehensive full-stack HR Management System with React 19 and Node.js, featuring employee management, attendance tracking, payroll processing, leave management, and performance reviews — all backed by a PostgreSQL database.",
    tech: ["React", "Node.js", "PostgreSQL", "Express"],
    features: [
      "Employee directory & profiles",
      "Attendance tracking",
      "Payroll processing",
      "Leave management",
      "Performance reviews",
      "Role-based access control",
    ],
    category: "Full Stack",
    gradient: "from-emerald-500 to-teal-600",
    year: "2025",
    featured: false,
    tags: ["HR", "enterprise", "PostgreSQL"],
    github: "https://github.com/jeet310704/HR-ManagementSystem",
  },
  {
    id: "alvyto",
    title: "Alvyto – AI Smart EMR",
    description: "Privacy-first AI-powered electronic medical records platform",
    longDescription:
      "A privacy-first Exam Room EMR that records medical consultations using on-device speech-to-text (Faster-Whisper), speaker diarization, and AI-generated visit summaries. Designed to help healthcare providers focus on patient care over paperwork.",
    tech: ["Next.js", "FastAPI", "Python", "AI APIs"],
    features: [
      "On-device speech-to-text",
      "Speaker diarization",
      "AI visit summaries",
      "Appointment scheduling",
      "Role-based access control",
      "Privacy-first architecture",
    ],
    category: "AI/ML",
    gradient: "from-cyan-500 to-blue-600",
    year: "2024",
    featured: true,
    tags: ["healthcare", "speech-to-text", "EMR"],
    github: "https://github.com/jeet310704/Alvyto",
  },
  {
    id: "sales-analytics",
    title: "Sales Analytics Dashboard",
    description: "End-to-end sales pipeline with Python, SQL, and Power BI",
    longDescription:
      "An end-to-end analytics pipeline that cleans and transforms raw CSV sales data using Pandas, runs business analysis queries in SQLite, and surfaces interactive Power BI dashboards. Covers revenue, profit, product performance, regional breakdowns, and customer segments.",
    tech: ["Python", "Pandas", "SQL", "Power BI", "SQLite"],
    features: [
      "Raw CSV data cleaning",
      "SQL business analysis queries",
      "Revenue & profit reporting",
      "Regional performance breakdown",
      "Customer segment analysis",
      "Interactive Power BI dashboard",
    ],
    category: "Data Analytics",
    gradient: "from-orange-500 to-amber-600",
    year: "2025",
    featured: true,
    tags: ["analytics", "Power BI", "SQL"],
    github: "https://github.com/jeet310704/sales-analytics-dashboard",
  },
  {
    id: "customer-churn",
    title: "Customer Churn Analysis",
    description: "ML-powered churn prediction with SQL analysis and visualizations",
    longDescription:
      "An end-to-end churn analysis pipeline covering data generation, SQL analysis, EDA, a Random Forest classification model, and a Tableau dashboard export. Explores tenure, charges, contract type, and payment method to identify key churn drivers and support retention strategy.",
    tech: ["Python", "Scikit-learn", "SQL", "Pandas", "Tableau"],
    features: [
      "Churn driver exploration & EDA",
      "SQL aggregation queries",
      "Random Forest ML model",
      "Segment-level churn rates",
      "Retention strategy insights",
      "Tableau dashboard export",
    ],
    category: "Data Analytics",
    gradient: "from-rose-500 to-red-600",
    year: "2025",
    featured: false,
    tags: ["machine learning", "churn", "classification"],
    github: "https://github.com/jeet310704/Customer-Churn-Analysis-Prediction",
  },
];

export const experiences: Experience[] = [
  {
    id: "concat-string",
    role: "AI/ML Intern",
    company: "ConcatString",
    period: "May 2026 – Present",
    type: "Internship",
    description: [
      "Design and build AI-integrated projects independently, applying machine learning to practical business use cases",
      "Helped automate the inventory management process, reducing manual effort and improving operational efficiency",
      "Manage day-to-day inventory operations while developing AI-driven tools to streamline internal workflows",
      "Process inventory and supply-chain documents by converting invoice PDFs into EDI formats using internal parsing systems",
    ],
    tech: ["Python", "AI/ML", "EDI", "PDF Parsing", "Data Transformation"],
  },
  {
    id: "silver-touch",
    role: "Web Development Intern",
    company: "Silver Touch Technologies",
    period: "June 2025",
    type: "Internship",
    description: [
      "Developed responsive, cross-browser web interfaces using HTML, CSS, and JavaScript for production projects",
      "Implemented UI components and resolved bugs, improving page performance and overall user experience",
      "Applied clean-code practices and version control while collaborating within a real-world development team",
      "Delivered client-facing features under production timelines following industry-standard Git workflows",
    ],
    tech: ["HTML", "CSS", "JavaScript", "React", "Tailwind CSS", "Git"],
  },
];

export const education: Education = {
  institution: "Indus University",
  degree: "Bachelor of Technology (B.Tech)",
  field: "Computer Science Engineering",
  gpa: "8.79",
  period: "2022 – 2026",
  graduated: true,
  icon: "🎓",
};

export const skillCategories: SkillCategory[] = [
  {
    name: "Frontend",
    icon: "⚡",
    color: "from-yellow-400 to-orange-500",
    skills: ["React", "Next.js", "TypeScript", "JavaScript", "Tailwind CSS"],
  },
  {
    name: "Backend",
    icon: "🔧",
    color: "from-green-400 to-emerald-600",
    skills: ["Node.js", "Express.js", "FastAPI", "REST APIs", "JWT Auth"],
  },
  {
    name: "Data & Analytics",
    icon: "📊",
    color: "from-orange-400 to-amber-500",
    skills: ["Python", "Pandas", "NumPy", "Scikit-learn", "SQL", "Power BI", "Tableau", "EDA"],
  },
  {
    name: "Database",
    icon: "🗄️",
    color: "from-blue-400 to-cyan-500",
    skills: ["MongoDB", "PostgreSQL", "Supabase", "SQLite"],
  },
  {
    name: "AI / ML",
    icon: "🤖",
    color: "from-purple-500 to-violet-600",
    skills: ["Gemini API", "Prompt Engineering", "Machine Learning", "AI Integration"],
  },
  {
    name: "Tools",
    icon: "🛠️",
    color: "from-pink-400 to-rose-600",
    skills: ["Git", "GitHub", "Vercel", "Render", "Cloudinary"],
  },
];

export const stats: Stat[] = [
  { label: "Projects Built", value: 6, suffix: "+" },
  { label: "Technologies", value: 18, suffix: "+" },
  { label: "Internships", value: 2, suffix: "" },
  { label: "Active Internship", value: 1, suffix: "" },
];

export const techStack = [
  "React",
  "Next.js",
  "TypeScript",
  "Python",
  "Pandas",
  "SQL",
  "Power BI",
  "FastAPI",
  "Express.js",
  "MongoDB",
  "PostgreSQL",
  "Supabase",
  "Tailwind CSS",
  "Scikit-learn",
  "Tableau",
  "Socket.IO",
  "Gemini API",
  "Git",
  "Node.js",
];

export const personalInfo = {
  name: "Jeet Patel",
  title: "Full-Stack Developer & Data Analyst",
  tagline: "Building web apps and data solutions — from React frontends to Python analytics pipelines.",
  email: "jeet310704@gmail.com",
  github: "https://github.com/jeet310704",
  linkedin: "https://www.linkedin.com/in/jeet3174/",
  location: "Ahmedabad, India",
  available: true,
};
